version: '3'
services:
  web:
    build:
      dockerfile: ./Dockerfile
    container_name: web
    ports:
      - "8000:80"
    volumes:
      - ./my-project/public:/var/www/html
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: symfony
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db

volumes:
  db_data: