version: '3'
services:
  web:
    build:
      dockerfile: ./Dockerfile
    container_name: web
    ports:
      - 8000:80
    volumes:
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: symfony
      MYSQL_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

volumes:
  db_data: